window.demandas = [
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us1",
    "tipo_us": "USF+",
    "tipo_demanda": "eletrica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us2",
    "tipo_us": "USF+",
    "tipo_demanda": "eletrica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us3",
    "tipo_us": "USF+",
    "tipo_demanda": "eletrica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us4",
    "tipo_us": "USF+",
    "tipo_demanda": "hidraulica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us5",
    "tipo_us": "USF+",
    "tipo_demanda": "hidraulica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us6",
    "tipo_us": "USF+",
    "tipo_demanda": "hidraulica",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us7",
    "tipo_us": "USF+",
    "tipo_demanda": "infraestrutura",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us8",
    "tipo_us": "USF+",
    "tipo_demanda": "infraestrutura",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us9",
    "tipo_us": "USF+",
    "tipo_demanda": "infraestrutura",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us10",
    "tipo_us": "USF+",
    "tipo_demanda": "climatizacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us11",
    "tipo_us": "USF+",
    "tipo_demanda": "climatizacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us12",
    "tipo_us": "USF+",
    "tipo_demanda": "climatizacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us13",
    "tipo_us": "USF+",
    "tipo_demanda": "capinacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us14",
    "tipo_us": "USF+",
    "tipo_demanda": "capinacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us15",
    "tipo_us": "USF+",
    "tipo_demanda": "capinacao",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us15",
    "tipo_us": "USF+",
    "tipo_demanda": "reparos",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us16",
    "tipo_us": "USF+",
    "tipo_demanda": "reparos",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us17",
    "tipo_us": "USF+",
    "tipo_demanda": "reparos",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us18",
    "tipo_us": "USF+",
    "tipo_demanda": "bens-inserviveis",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us19",
    "tipo_us": "USF+",
    "tipo_demanda": "bens-inserviveis",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us20",
    "tipo_us": "USF+",
    "tipo_demanda": "bens-inserviveis",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us21",
    "tipo_us": "USF+",
    "tipo_demanda": "almoxarifado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us22",
    "tipo_us": "USF+",
    "tipo_demanda": "almoxarifado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us23",
    "tipo_us": "USF+",
    "tipo_demanda": "almoxarifado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us24",
    "tipo_us": "USF+",
    "tipo_demanda": "agua-mineral",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us25",
    "tipo_us": "USF+",
    "tipo_demanda": "agua-mineral",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us25",
    "tipo_us": "USF+",
    "tipo_demanda": "agua-mineral",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us26",
    "tipo_us": "USF+",
    "tipo_demanda": "carro-pipa",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us27",
    "tipo_us": "USF+",
    "tipo_demanda": "carro-pipa",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us28",
    "tipo_us": "USF+",
    "tipo_demanda": "carro-pipa",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us28",
    "tipo_us": "USF+",
    "tipo_demanda": "lixo-infectado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us28",
    "tipo_us": "USF+",
    "tipo_demanda": "lixo-infectado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "em atendimento",
    "status": "pendente",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us28",
    "tipo_us": "USF+",
    "tipo_demanda": "lixo-infectado",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "em atendimento",
    "status": "pendente",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us29",
    "tipo_us": "USF+",
    "tipo_demanda": "poda",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us29",
    "tipo_us": "USF+",
    "tipo_demanda": "poda",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "recebido",
    "status": "pendente",
    "dt_registro": "2025-02-05T00:31:43.533626"
  },
  {
    "id": 1,
    "n_demanda": 1,
    "solicitante": "Bruno",
    "us": "us30",
    "tipo_us": "USF+",
    "tipo_demanda": "poda",
    "desc_demanda": "desc",
    "img_url": "img",
    "dt_demanda": "2025-12-15",
    "andamento": "em atendimento",
    "status": "pendente",
    "dt_registro": "2025-02-05T00:31:43.533626"
  }
  
]
