window.demandas = [
  {
    "id": 68,
    "n_demanda": 2025010,
    "solicitante": "Carla Costa",
    "us": "USF BRASILIT",
    "tipo_us": "USF",
    "tipo_demanda": "capinacao",
    "desc_demanda": "terreno abandonado",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "finalizado",
    "status": "nao resolvido",
    "observacao": "\\zsxdasdxasd",
    "dt_registro": "2025-03-23"
  },
  {
    "id": 60,
    "n_demanda": 2025002,
    "solicitante": "Carlos Silva",
    "us": "USF MAIS MISTA OLINTO OLEVEIRA",
    "tipo_us": "USF+",
    "tipo_demanda": "eletrica",
    "desc_demanda": "sem luz",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-20"
  },
  {
    "id": 61,
    "n_demanda": 2025003,
    "solicitante": "Ana Costa",
    "us": "USF MAIS CARANGUEJO",
    "tipo_us": "USF+",
    "tipo_demanda": "hidraulica",
    "desc_demanda": "falta de agua",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-20"
  },
  {
    "id": 62,
    "n_demanda": 2025004,
    "solicitante": "João Pereira",
    "us": "USF MAIS VILA ARRAES",
    "tipo_us": "USF+",
    "tipo_demanda": "poda",
    "desc_demanda": "árvore caindo",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-20"
  },
  {
    "id": 63,
    "n_demanda": 2025005,
    "solicitante": "Maria Souza",
    "us": "USF MAIS JARDIM TERESÓPOLIS",
    "tipo_us": "USF+",
    "tipo_demanda": "infraestrutura",
    "desc_demanda": "buraco na rua",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-20"
  },
  {
    "id": 65,
    "n_demanda": 2025007,
    "solicitante": "Paulo Oliveira",
    "us": "USF AMAURY DE MEDEIROS",
    "tipo_us": "USF",
    "tipo_demanda": "climatizacao",
    "desc_demanda": "ar condicionado quebrado",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-22"
  },
  {
    "id": 67,
    "n_demanda": 2025009,
    "solicitante": "Fábio Almeida",
    "us": "USF BARREIRAS",
    "tipo_us": "USF",
    "tipo_demanda": "carro-pipa",
    "desc_demanda": "falta de água",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "recebido",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-23"
  },
  {
    "id": 69,
    "n_demanda": 2025011,
    "solicitante": "Ricardo Martins",
    "us": "USF ROSA SELVAGEM",
    "tipo_us": "USF",
    "tipo_demanda": "bens-inserviveis",
    "desc_demanda": "geladeira quebrada",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "finalizado",
    "status": "resolvido",
    "observacao": "666666",
    "dt_registro": "2025-03-23"
  },
  {
    "id": 70,
    "n_demanda": 2025012,
    "solicitante": "Bruno Gama",
    "us": "teste",
    "tipo_us": "usf",
    "tipo_demanda": "eletrica",
    "desc_demanda": "sem luz",
    "img_url": null,
    "dt_demanda": "2025-03-15",
    "andamento": "finalizado",
    "status": "resolvido",
    "observacao": "resolvido",
    "dt_registro": "2025-03-24"
  },
  {
    "id": 66,
    "n_demanda": 2025008,
    "solicitante": "Lucia Fernandes",
    "us": "USF COSME E DAMIÃO",
    "tipo_us": "USF",
    "tipo_demanda": "reparos",
    "desc_demanda": "janela quebrada",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "em atendimento",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-22"
  },
  {
    "id": 64,
    "n_demanda": 2025006,
    "solicitante": "Rita Lima",
    "us": "USF MAIS EMOCY KRAUSE",
    "tipo_us": "USF+",
    "tipo_demanda": "eletrica",
    "desc_demanda": "cabo partido",
    "img_url": null,
    "dt_demanda": "2025-03-19",
    "andamento": "em atendimento",
    "status": "pendente",
    "observacao": null,
    "dt_registro": "2025-03-22"
  }
]