window.demandas = [
    {
      "id": 1,
      "n_demanda": 1,
      "solicitante": "Bruno",
      "us": "us1",
      "tipo_us": "USF+",
      "tipo_demanda": "Elétrica",
      "desc_demanda": "desc",
      "img_url": "img",
      "dt_demanda": "2025-12-15",
      "andamento": "recebido",
      "status": "pendente"
    },
    {
      "id": 2,
      "n_demanda": 2,
      "solicitante": "Ana",
      "us": "us2",
      "tipo_us": "USF",
      "tipo_demanda": "Climatização",
      "desc_demanda": "ar condicionado quebrou",
      "img_url": null,
      "dt_demanda": "2025-01-31",
      "andamento": "recebido",
      "status": "pendente"
    },
    {
      "id": 3,
      "n_demanda": 3,
      "solicitante": "Carlos",
      "us": "us3",
      "tipo_us": "USF+",
      "tipo_demanda": "Poda",
      "desc_demanda": "mato na entrada",
      "img_url": null,
      "dt_demanda": "2025-02-02",
      "andamento": null,
      "status": "Pendente"
    },
    {
      "id": 5,
      "n_demanda": 5,
      "solicitante": "Edésio",
      "us": "US5",
      "tipo_us": "USF+",
      "tipo_demanda": "Almoxarifado",
      "desc_demanda": "sem lápis",
      "img_url": null,
      "dt_demanda": "2025-02-02",
      "andamento": "Finalizado",
      "status": "resolvido"
    },
    {
      "id": 6,
      "n_demanda": null,
      "solicitante": "Fabio",
      "us": "US7",
      "tipo_us": "USF",
      "tipo_demanda": "agua-mineral",
      "desc_demanda": "sem agua",
      "img_url": "",
      "dt_demanda": "2025-02-03",
      "andamento": "em atendimento",
      "status": "Pendente"
    },
    {
      "id": 8,
      "n_demanda": 9,
      "solicitante": "Papaguaio",
      "us": "teste",
      "tipo_us": "usf+",
      "tipo_demanda": "Hidráulica",
      "desc_demanda": "sem cano",
      "img_url": null,
      "dt_demanda": "2025-02-03",
      "andamento": "em atendimento",
      "status": "Pendente"
    },
    {
      "id": 9,
      "n_demanda": 10,
      "solicitante": "Lucas",
      "us": "us10",
      "tipo_us": "usf+",
      "tipo_demanda": "agua-mineral",
      "desc_demanda": "sem agua",
      "img_url": null,
      "dt_demanda": "2025-02-03",
      "andamento": "em atendimento",
      "status": "Pendente"
    },
    {
      "id": 10,
      "n_demanda": 11,
      "solicitante": "Pedro",
      "us": "us11",
      "tipo_us": "usf+",
      "tipo_demanda": "Reparos",
      "desc_demanda": "maçaneta quebrou",
      "img_url": null,
      "dt_demanda": "2025-02-03",
      "andamento": "em atendimento",
      "status": "Pendente"
    },
    {
      "id": 11,
      "n_demanda": 11,
      "solicitante": "Aldo",
      "us": "usf",
      "tipo_us": "usf+",
      "tipo_demanda": "Elétrica",
      "desc_demanda": "faltou energia",
      "img_url": null,
      "dt_demanda": "2025-02-03",
      "andamento": "em atendimento",
      "status": "Pendente"
    },
    {
      "id": 12,
      "n_demanda": null,
      "solicitante": "Simone",
      "us": "us12",
      "tipo_us": "usf+",
      "tipo_demanda": "Carro-pipa",
      "desc_demanda": "carro-pipa",
      "img_url": null,
      "dt_demanda": "2025-02-03",
      "andamento": "finalizado",
      "status": "resolvido"
    }
  ]
